### ISSUE TITLE
FoundLibDevice not correctly checked

### ISSUE THREAD

**Issue by hahnjo** [clang-omp/clang_trunk#12]
Don't know whether this is the correct place for this...

In lib/Driver/Tools.cpp the CUDA library "libdevice" is searched when linking for NVPTX with -lm. There is a variable to test whether the files have been found, but it is never checked when building for Release (assert is empty then?)

**Comment by sfantao** [comment]
Hi Jonas,

The driver tries to get the math lib implementation from the user CUDA
installation when the target is nvptx. In order for that to work -L or
LIBRARY_PATH have to be set.

I agree that the check should not be done as an assertion, but emit a
proper diagnostic message. That should be fixed now.

Thanks for reporting the issue!
Samuel

**Comment by hahnjo** [comment]
I understood the requirement, I only wanted to point to the "error message".
Thanks for the fix!
