### ISSUE TITLE
Compile error with math.h, -omptargets and optimization

### ISSUE THREAD

**Issue by hahnjo** [clang-omp/clang_trunk#13]
First: Is it ok to open issues with bugs or is it too early in the development process?

` math.c `
```C
#include <math.h>
```
` $ clang -fopenmp -omptargets=nvptx64sm_35-nvidia-cuda -c math.c ` works
` $ clang -fopenmp -omptargets=nvptx64sm_35-nvidia-cuda -O3 -c math.c ` gives compile errors:
```
In file included from math.c:1:
In file included from /usr/include/math.h:416:
/usr/include/bits/mathinline.h:45:43: error: invalid input constraint 'x' in asm
  __asm ("pmovmskb %1, %0" : "=r" (__m) : "x" (__x));
                                          ^
/usr/include/bits/mathinline.h:57:43: error: invalid input constraint 'x' in asm
  __asm ("pmovmskb %1, %0" : "=r" (__m) : "x" (__x));
                                          ^
2 errors generated.
```
If I understand this correctly, it fails when compiling for the GPU because it does not recognize the x constraint which is specific for x86.

Environment: Scientifc Linux 6.6, CUDA 7.0.28

**Comment by sfantao** [comment]
I've had trouble getting a machine where math.h has inlined assembly. Can
you by any chance share your math.h here?

Thanks,
Samuel

**Comment by hahnjo** [comment]
They seem to be standard from glibc:
https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=math/math.h;hb=HEAD
https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/x86/fpu/bits/mathinline.h;hb=HEAD

When enabling optimization, clang seems to define __USE_EXTERN_INLINES. Maybe it's just sufficient to not do this when compiling for the target...

**Comment by hahnjo** [comment]
Ok, so __USE_EXTERN_INLINES comes from here and probably cannot be undefined:
https://raw.githubusercontent.com/gcc-mirror/gcc/master/fixincludes/tests/base/features.h

But __SSE2_MATH__ comes from here and may not be set when compiling for the target:
https://github.com/clang-omp/clang_trunk/blob/master/lib/Basic/Targets.cpp#L3251

**Comment by sfantao** [comment]
Ok, thanks for the pointer. I'll continue investigating this later today.

Thanks again,
Samuel

**Comment by sfantao** [comment]
This should now be fixed by https://github.com/clang-omp/clang_trunk/issues/15.

Thanks for reporting the issue!
Samuel

**Comment by hahnjo** [comment]
Yep, thanks!

Have some other issues right now, but these are probably related to upstream changes....
