### ISSUE TITLE
compile error: Never resolved value found in function

### ISSUE THREAD

**Issue by hahnjo** [clang-omp/clang_trunk#14]
```C
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char* argv[])
{
	const int n = 1024;
	int i, j;

	#pragma omp target teams private(j)
	for (i = 0; i < n; i++) {
		
	}

	return EXIT_SUCCESS;
}
```

Fails to compile because `j` is not used? This error also triggers with a more complex scenario where `j` is only used within another outlined omp function...

**Comment by hahnjo** [comment]
Just noticed that this is the same error message you were referring to yesterday:
https://github.com/clang-omp/libomptarget/pull/1#issuecomment-111190981

**Comment by sfantao** [comment]
Hi Jonas,

Thanks for reporting the issue. I am fixing a few issues in combined
directives, hopefully this will also been taken care of. I should be able
to update the code in a few days.

Thanks again,
Samuel

**Comment by sfantao** [comment]
This should be fixed now. Please verify.

Thanks!
Samuel

**Comment by hahnjo** [comment]
Now working correctly!

Thanks,
Jonas
