### ISSUE TITLE
Error when compiling libdevice for sm_35

### ISSUE THREAD

**Issue by hahnjo** [clang-omp/clang_trunk#16]
When linking with `-lm` in target mode clang builds the libdevice for math functions on the device.

When compiling for `nvptx64sm_35-nvidia-cuda`, I get the following error multiple times:
```
error   : Feature 'rsqrt.approx.ftz.f64' requires PTX ISA .version 4.0 or later
```

The reason is that clang defaults to PTX 3.2 for `sm_35`. I see two alternatives:
1. Ask upstream devs to bump default PTX version to 4.0 or even 4.2
2. Pass `-mattr=ptx42` when calling `llc`.
```diff
diff --git a/lib/Driver/Tools.cpp b/lib/Driver/Tools.cpp
index fbdb88e..7ab3968 100644
--- a/lib/Driver/Tools.cpp
+++ b/lib/Driver/Tools.cpp
@@ -9283,6 +9283,7 @@ static void BitcodeToCubin(Compilation &C, const JobAction &JA, const Tool &T,
   if (!CPU.empty()) {
     std::string CPUFlag = "-mcpu=" + CPU;
     LlcCmdArgs.push_back(C.getArgs().MakeArgString(CPUFlag));
+    LlcCmdArgs.push_back(C.getArgs().MakeArgString("-mattr=ptx42"));
   }
   const char *LlcExec = Args.MakeArgString(TC.getDriver().Dir + "/llc");
   C.addCommand(llvm::make_unique<Command>(JA, T, LlcExec, LlcCmdArgs));
```

I don't know if there are any compatibility issues, but it works in my case...

**Comment by sfantao** [comment]
Hi hahnjo,

Thanks for reporting the issue. what CUDA version are you using? Just wondering if for some reason the version I have for PPC is not the latest and therefore does not expose the issue.

Thanks again!
Samuel

**Comment by hahnjo** [comment]
Hi Samuel,

I'm using CUDA 7.0.28 for Linux. Could you possibly be using any kind of system default libdevice? The issue is only occuring since 6.5...

Also are you using exactly `sm_35`? `sm_32` for example uses PTX 4.0 by default: https://github.com/clang-omp/llvm_trunk/blob/master/lib/Target/NVPTX/NVPTX.td#L68

Thanks,
Jonas

**Comment by sfantao** [comment]
This should now be fixed. The math library is now being generated with PTX 4.0 support.

Thanks!
Samuel

**Comment by hahnjo** [comment]
Now working, thanks!
Jonas
