### ISSUE TITLE
Illegal NVPTX instruction with simd

### ISSUE THREAD

**Issue by hahnjo** [clang-omp/clang_trunk#24]
(This code makes no sense but shows the problem:)
```C
#include <stdlib.h>

int main(int argc, char* argv[])
{
	float a = 1.0, b = 2.0, r;
	#pragma omp target teams distribute parallel for simd
	for (size_t i = 0; i < 1024; i++) {
		r = a + b;
	}

	return EXIT_SUCCESS;
}
```

Output (libomptarget in debug mode):
```
[...]
Target CUDA RTL --> launch kernel with 14 blocks and 1024 threads
Target CUDA RTL --> Execution of entry point at 0000000000a53f20 successful!
Libomptarget --> There are 4 bytes allocated at target address 000000135a440000 - is last 1
Libomptarget --> Moving 4 bytes (tgt:000000135a440000) -> (hst:00007ffde0d7f164)
Target CUDA RTL --> Error when copying data from device to host. Pointers: host = 0x00007ffde0d7f164, device = 0x000000135a440000, size = 4
Target CUDA RTL --> CUDA error is: an illegal instruction was encountered
Libomptarget --> Deleting tgt data 0x000000135a440000 of size 4
[...]
```
The error probably happens during execution, not during data movement...

**Comment by hahnjo** [comment]
Compiled with `clang -fopenmp -O3 -omptargets=nvptx64sm_35-nvidia-cuda simd.c -o simd.exe`.

This also shows
```
warning: loop not vectorized: failed explicitly specified loop vectorization [-Wpass-failed]
```

I'm also getting this warning with simd loops for the host. Upstream trunk doesn't show this, runtime is the same...

**Comment by hahnjo** [comment]
Great example: With `-O0` I'm facing `error: Invalid record`
I have already seen this multiple times but wasn't really able to reproduce...

**Comment by hahnjo** [comment]
Ok, so last note from my side:
Looking at the LLVM IR, I see the following block that seems to trigger:
```LLVM
.lane.not.in.excess.:                             ; preds = %.start.simd.
  call void @llvm.trap()
  unreachable
```

It should came from the `BasicBlock` in function `CGOpenMPRuntime_NVPTX::EnterSimdRegion` in `CGOpenMPRuntime.cpp`. But I really don't know why it is generating the call to `@llvm.trap()`...

**Comment by carlobertolli** [comment]
Hi

I am looking at the problem on the nvptx backend side. I think that the following:

warning: loop not vectorized: failed explicitly specified loop vectorization [-Wpass-failed]

is only valid for the host. That is, there is no vectorization capability on the ptx side and I suspect that the report is only valid for the host. Does this make sense to you?

Thanks!

-- Carlo

**Comment by hahnjo** [comment]
Hi,

that could be the explanation for this warning. It also happens with code that has no target region at all (but not with all omp simds though...)
Looking at the output when invoking `clang` with `-v` also shows that the warning is issued during compilation for host.

But why does it show up with `clang-omp` but not with upstream `trunk`?

Cheers,
Jonas

**Comment by carlobertolli** [comment]
Hi

I tried this example and I get a compiler error:

clang-3.8: /localhd/cbertol/src/lib/IR/Instructions.cpp:2553: static llvm::CastInst *llvm::CastInst::Create(Instruction::CastOps, llvm::Value *, llvm::Type *, const llvm::Twine &, llvm::Instruction *): Assertion `castIsValid(op, S, Ty) && "Invalid cast!"' failed.

I know what the problem is and have already fixed it in our local repo. I should be able to produce a patch soon. I am working on the github/master branch - can you please verify if you are up-to-date with it?


Cheers

-- Carlo

**Comment by hahnjo** [comment]
Hi Carlo,

great if you already have a fix, that was fast!
Yes, I should be up to date: llvm_trunk is exactly github/master and clang_trunk has a few patches applied locally: my two pull requests + switch of default C++ lib...

Jonas

**Comment by carlobertolli** [comment]
It was an easy one..do you have a branch in your public repo that I can try locally?
I think we are looking at different codes.

Thanks

-- Carlo

**Comment by hahnjo** [comment]
The two merge requests are public, the other commit is only one line that has nothing to do with OpenMP.

But I've found the difference: I'm using Release builds so assertions won't trigger. I'm sorry, I will switch back to Debug builds and then expect to see your compiler error.

Greetings
Jonas

**Comment by hahnjo** [comment]
Ok then, I can now exactly reproduce your compiler error.

Sorry again
Jonas
